# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b_ClI8-lIVjyYQ5Z_24bYevYMSPlAcez
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("/content/placementdata.csv")
df.head()

df['CGPA'].describe()

df.info()

df.isnull().sum()

df.drop("StudentID", axis=1, inplace=True)

df["ExtracurricularActivities"] = df["ExtracurricularActivities"].map({"Yes": 1, "No": 0})
df["PlacementTraining"] = df["PlacementTraining"].map({"Yes": 1, "No": 0})

df["PlacementStatus"] = df["PlacementStatus"].map({
    "Placed": 1,
    "NotPlaced": 0
})

print(df["PlacementStatus"].unique())  # must be [0 1]

X = df.drop("PlacementStatus", axis=1)
y = df["PlacementStatus"]

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.25, random_state=0, stratify=y)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

new_student_original_cgpa = 5.5   # change this value as needed

new_student = np.array([[
    new_student_original_cgpa,  # CGPA
    78,    # SSC_Marks
    82,    # HSC_Marks
    1,     # Internships
    3,     # Projects
    2,     # Workshops/Certifications
    85,    # AptitudeTestScore
    4,     # SoftSkillsRating
    1,     # ExtracurricularActivities
    1      # PlacementTraining
]])

new_student_scaled = scaler.transform(new_student)

if new_student_original_cgpa < 6.0:
    print("Student is likely to be NOT PLACED (CGPA below cutoff)")
else:
    prediction = model.predict(new_student_scaled)
    if prediction[0] == 1:
        print("Student is likely to be PLACED")
    else:
        print("Student is likely to be NOT PLACED")

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
}).sort_values(by="Importance", ascending=False)

print(importance)

new_student_original_cgpa = 8.5

new_student = np.array([[
    new_student_original_cgpa,  # CGPA
    78,    # SSC_Marks
    82,    # HSC_Marks
    1,     # Internships
    3,     # Projects
    2,     # Workshops/Certifications
    85,    # AptitudeTestScore
    4,     # SoftSkillsRating
    1,     # ExtracurricularActivities
    1      # PlacementTraining
]])

# Optional CGPA rule
if new_student_original_cgpa < 6.0:
    print("❌ Student is likely to be NOT PLACED (CGPA below cutoff)")
else:
    prediction = rf_model.predict(new_student)
    if prediction[0] == 1:
        print("🎉 Student is likely to be PLACED")
    else:
        print("❌ Student is likely to be NOT PLACED")

from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=5,
    random_state=42
)

dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))
print(confusion_matrix(y_test, dt_pred))
print(classification_report(y_test, dt_pred))

new_student_original_cgpa = 8.5

new_student = np.array([[
    new_student_original_cgpa,
    78,
    82,
    1,
    3,
    2,
    85,
    4,
    1,
    1
]])

if new_student_original_cgpa < 6.0:
    print("❌ Student is likely to be NOT PLACED (CGPA below cutoff)")
else:
    prediction = rf_model.predict(new_student)
    if prediction[0] == 1:
        print("🎉 Student is likely to be PLACED")
    else:
        print("❌ Student is likely to be NOT PLACED")